### ISSUE TITLE
Add default Dockerfile

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-profiles#33]
Example:  https://github.com/micronaut-projects/micronaut-examples/blob/master/petstore/comments/Dockerfile

**Comment by ZacharyKlein** [comment]
One issue is that we have to hardcode the version of the app (`0.1`) in the name of the build artifact. I'm not sure how to work around this since the version could potentially be changed and that would require updating the Dockerfile. Ideally we could load this value from an environment variable but I'm not sure how to set that.

**Comment by graemerocher** [comment]
The Dockerfile for openfaas already has a workaround for this

**Comment by graemerocher** [comment]
@ZacharyKlein please take a look at this too
